name: dartrocket
version: 0.1.1
author: Tóth Róbert <kkdstryker@gmail.com>
description: DartRocket is a HTML5 game framework written in Dart and which uses the StageXL rendering engine.
homepage: https://github.com/StrykerKKD/dartrocket
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  stagexl: '>=0.9.2+1 <0.10.0'
